Create 0012-tsi-fix-selinux-errors.patch
Add tsi sockets to selinux classmap and hooks lists. Change required to build defconfig target for x86_64 on Linux at v6.0.2.

Fixes the following two errors:
security/selinux/hooks.c:1261:2: error: #error New address family defined, please update this function.
 1261 | #error New address family defined, please update this function.

security/selinux/include/classmap.h:261:2: error: #error New address family defined, please update secclass_map.
  261 | #error New address family defined, please update secclass_map.

Signed-off-by: Andrew Fasano <fasano@mit.edu>