Add missing elftools to build-on-krunvm.sh
Running `./build_on_krunvm.sh`, the kernel build works fine, but fails near the
end with

```
  OBJCOPY arch/arm64/boot/Image
  GZIP    arch/arm64/boot/Image.gz
make[1]: Leaving directory '/work/linux-6.1.32'
Generating kernel.c from linux-6.1.32/arch/arm64/boot/Image...
Traceback (most recent call last):
  File "/work/bin2cbundle.py", line 4, in <module>
    from elftools.elf.elffile import ELFFile
ModuleNotFoundError: No module named 'elftools'
```

There is a missing package `python3-pyelftools`.

Also replaced the explicit list of packages to install with an installation
of `dnf builddep` and using the depedencies for the kernel package.

Fixes #52

Signed-off-by: Christophe de Dinechin <christophe@dinechin.org>